# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               YUZ.ME
tagline:             'A few words about everything.'
description:         'This is a personal website, written with ♥ by YU Zijie.'
url:                 http://yuz.me
baseurl:             /
paginate:            1

# About/contact
author:
  name:              YU Zijie
  url:               http://yuz.me
  email:             feedback@yuz.me
