# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Small talk
tagline:             'A few words about everything.'
description:         'This is a personal website, written with <3 by YU Zijie.'
url:                 http://yuz.me
baseurl:             /
paginate:            3

# About/contact
author:
  name:              YU Zijie
  url:               http://yuz.me
  email:             feedback@yuz.me

# Custom vars
version:             1.0.0
